### ISSUE TITLE
Extra step is needed to enable "write" permissions from actions

### ISSUE THREAD

**Issue by lrivallain** [microsoft/anyonecancode#32]
Hi Team,

Had an issue with the deploy step of the workflow used on day 1: https://github.com/lrivallain/anyonecancode/actions/runs/4719763270/attempts/1 with permissions of the GH actions.

> fatal: unable to access 'https://github.com/lrivallain/anyonecancode.git/': The requested URL returned error: 403

Seems that an extra step is needed to enable "write" permissions from actions (either configuration on repository settings or in the workflow file):

> [Adding permission in the config file works, and you can also modify the GitHub Actions settings of your repository to enable write permissions without modifying the config file.](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository)

**Comment by waeltken** [comment]
Fixed
